language: python

matrix:
  include:
  - os: linux
    sudo: required
    python: 3.6
    dist: trusty

before_install:
- pip install -U pip

install:
- travis_wait pip install -r test_requirements.txt

addons:
  sauce_connect:
    username: "chrisjsewell"
    access_key: "2428b132-dd74-4326-a484-95eace873558"

script:
- py.test

